{ config, lib, pkgs, ... }:

let
  # Generated by `mergiraf languages --gitattributes` (v0.16.1). Mergiraf
  # only engages on these patterns and falls back to a normal 3-way merge
  # when structured merging fails, so the broad list is safe.
  mergirafAttributes = [
    "*.java merge=mergiraf"
    "*.properties merge=mergiraf"
    "*.kt merge=mergiraf"
    "*.rs merge=mergiraf"
    "*.go merge=mergiraf"
    "go.mod merge=mergiraf"
    "go.sum merge=mergiraf"
    "go.work.sum merge=mergiraf"
    "*.ini merge=mergiraf"
    "*.js merge=mergiraf"
    "*.jsx merge=mergiraf"
    "*.mjs merge=mergiraf"
    "*.json merge=mergiraf"
    "*.yml merge=mergiraf"
    "*.yaml merge=mergiraf"
    "pyproject.toml merge=mergiraf"
    "*.toml merge=mergiraf"
    "*.html merge=mergiraf"
    "*.htm merge=mergiraf"
    "*.xhtml merge=mergiraf"
    "*.xml merge=mergiraf"
    "*.c merge=mergiraf"
    "*.h merge=mergiraf"
    "*.cc merge=mergiraf"
    "*.hh merge=mergiraf"
    "*.cpp merge=mergiraf"
    "*.hpp merge=mergiraf"
    "*.cxx merge=mergiraf"
    "*.hxx merge=mergiraf"
    "*.c++ merge=mergiraf"
    "*.h++ merge=mergiraf"
    "*.mpp merge=mergiraf"
    "*.cppm merge=mergiraf"
    "*.ixx merge=mergiraf"
    "*.tcc merge=mergiraf"
    "*.cs merge=mergiraf"
    "*.dart merge=mergiraf"
    "*.dts merge=mergiraf"
    "*.scala merge=mergiraf"
    "*.sbt merge=mergiraf"
    "*.ts merge=mergiraf"
    "*.tsx merge=mergiraf"
    "*.py merge=mergiraf"
    "*.php merge=mergiraf"
    "*.phtml merge=mergiraf"
    "*.php3 merge=mergiraf"
    "*.php4 merge=mergiraf"
    "*.php5 merge=mergiraf"
    "*.phps merge=mergiraf"
    "*.phpt merge=mergiraf"
    "*.sol merge=mergiraf"
    "*.lua merge=mergiraf"
    "*.rb merge=mergiraf"
    "*.ex merge=mergiraf"
    "*.exs merge=mergiraf"
    "*.nix merge=mergiraf"
    "*.sv merge=mergiraf"
    "*.svh merge=mergiraf"
    "*.md merge=mergiraf"
    "*.hcl merge=mergiraf"
    "*.tf merge=mergiraf"
    "*.tfvars merge=mergiraf"
    "*.ml merge=mergiraf"
    "*.mli merge=mergiraf"
    "*.hs merge=mergiraf"
    "*.mk merge=mergiraf"
    "Makefile merge=mergiraf"
    "GNUmakefile merge=mergiraf"
    "*.bzl merge=mergiraf"
    "*.bazel merge=mergiraf"
    "BUILD merge=mergiraf"
    "WORKSPACE merge=mergiraf"
    "*.cmake merge=mergiraf"
    "CMakeLists.txt merge=mergiraf"
  ];
in

{
  # Direnv + nix-direnv (auto-load project shells)
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
    enableZshIntegration = true;
  };

  # Git
  programs.git = {
    enable = true;
    lfs.enable = true;

    # Background gc/commit-graph/prefetch via systemd user timers. Repos
    # MUST be listed here: the HM-managed gitconfig is a read-only store
    # symlink, so `git maintenance register` cannot write to it.
    maintenance = {
      enable = true;
      repositories = [ "${config.home.homeDirectory}/code/nixos-config" ];
    };

    attributes = mergirafAttributes;

    settings = {
      # Identity is mkDefault so the work profile can override it with a
      # work name/email/key without touching this shared module.
      user.name = lib.mkDefault "Dustin Poage";
      user.email = lib.mkDefault "poage.dustin@gmail.com";
      init.defaultBranch = "main";
      pull.rebase = true;
      core.editor = "nvim";
      merge.conflictstyle = "zdiff3";
      diff.algorithm = "histogram";
      rerere.enable = true;

      # Sign commits/tags with the existing SSH key — no GPG keyring.
      # Upload the pubkey to GitHub as a *signing* key for "Verified".
      gpg.format = "ssh";
      user.signingkey = lib.mkDefault "${config.home.homeDirectory}/.ssh/id_ed25519.pub";
      commit.gpgsign = true;
      tag.gpgsign = true;

      # Structural diffs on demand via `git dft`; delta stays the pager
      # for regular `git diff`.
      difftool.prompt = false;
      difftool.difftastic.cmd = ''difft "$LOCAL" "$REMOTE"'';
      pager.difftool = true;
      alias.dft = "difftool -t difftastic";

      # Syntax-aware merge driver; opted in per filetype via the
      # attributes list above.
      merge.mergiraf = {
        name = "mergiraf";
        driver = "mergiraf merge --git %O %A %B -s %S -x %X -y %Y -p %P -l %L";
      };
    };
  };

  # Delta (better diffs)
  programs.delta = {
    enable = true;
    enableGitIntegration = true;
    options = {
      navigate = true;
      side-by-side = true;
      line-numbers = true;
    };
  };

  # GitHub CLI
  programs.gh = {
    enable = true;
    settings.git_protocol = "ssh";
  };

  # gh-dash — PR/issue TUI dashboard (`gh-dash`)
  programs.gh-dash.enable = true;

  # Jujutsu — git-compatible VCS. Try it on an existing repo with
  # `jj git init --colocate`; git and jj stay in sync in the same worktree.
  programs.jujutsu = {
    enable = true;
    settings.user = {
      name = "Dustin Poage";
      email = "poage.dustin@gmail.com";
    };
  };

  # SSH agent
  services.ssh-agent.enable = true;

  # nix-index + comma (run any nix package without installing)
  programs.nix-index = {
    enable = true;
    enableZshIntegration = true;
  };

  # Put `go install` output (GOPATH/bin) on PATH. Entries are expanded in a
  # double-quoted context, so $HOME resolves at session init. Lets binaries
  # like `go install github.com/dpoage/bugbot@latest` run by bare name.
  home.sessionPath = [ "$HOME/go/bin" ];

  home.packages = with pkgs; [
    comma
    cachix

    # Git tooling
    git-absorb # `git absorb` — auto-route fixup! commits to the right ancestor
    mergiraf # merge driver wired into programs.git above
    difftastic # structural diff, used by `git dft`

    # TypeScript / Node
    nodejs
    typescript
    nodePackages.typescript-language-server
  ];
}
