# Niri compositor config, themed from the active palette.
#
# Only activates when `myRice.compositor = "niri"`. Writes
# `~/.config/niri/config.kdl` via xdg.configFile because home-manager
# does not ship a `programs.niri` module on release-25.11.
#
# The KDL is intentionally focused on the *themed* parts of the rice
# (focus ring, border, shadow, animations, window rules, autostart for
# wallpaper + notification daemons). Hosts can drop additional KDL into
# `~/.config/niri/config.d/*.kdl` for machine-specific bits (output
# layouts, gaming workarounds, etc.) since niri reads that directory
# automatically.

{ config, lib, pkgs, ... }:

let
  cfg = config.myRice;
  c   = cfg.colors;
  isNiri = cfg.enable && cfg.compositor == "niri";
in
{
  config = lib.mkIf isNiri {
    # The niri NixOS module owns systemd session + xdg portal setup; the
    # binary itself is pulled in there. We still need a user-side install
    # for tools that other rice modules invoke (niri msg, validate).
    home.packages = [ pkgs.niri ];

    xdg.configFile."niri/config.kdl".text = ''
      // Generated by common/home/rice/niri.nix. Edit the nix module rather
      // than this file; home-manager will overwrite it on every switch.

      input {
          keyboard {
              xkb { }
              numlock
          }
          touchpad {
              tap
              natural-scroll
          }
      }

      layout {
          gaps 16
          center-focused-column "never"

          preset-column-widths {
              proportion 0.33333
              proportion 0.5
              proportion 0.66667
          }

          default-column-width { proportion 0.5; }

          focus-ring {
              width 3
              active-gradient from="#${c.accent}" to="#${c.accentTri}" angle=45 in="oklch longer hue"
              inactive-color "#${c.bg1}"
          }

          border {
              off
              width 1
              active-color "#${c.accentSecond}"
              inactive-color "#${c.bg2}"
              urgent-color "#${c.urgent}"
          }

          shadow {
              on
              softness 40
              spread 4
              offset x=0 y=8
              color "#${c.bg}cc"
          }

          struts { }
      }

      prefer-no-csd
      screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

      hotkey-overlay { }

      // Snappy spring-driven animations. Workspace switches and overview
      // open/close use springs; window open/close use ease-out curves so
      // they feel responsive without being abrupt.
      animations {
          slowdown 0.85
          workspace-switch {
              spring damping-ratio=1.0 stiffness=1000 epsilon=0.0001
          }
          window-open {
              duration-ms 180
              curve "ease-out-expo"
          }
          window-close {
              duration-ms 150
              curve "ease-out-quad"
          }
          horizontal-view-movement {
              spring damping-ratio=1.0 stiffness=800 epsilon=0.0001
          }
          overview-open-close {
              spring damping-ratio=1.0 stiffness=750 epsilon=0.0001
          }
      }

      // Window rules: rounded corners globally; alacritty active fully
      // opaque so wallpapers don't bleed into text; floating panels keep
      // a tighter corner radius and a hint of opacity.
      window-rule {
          geometry-corner-radius 10
          clip-to-geometry true
      }
      window-rule {
          match app-id="Alacritty" is-active=true
          opacity 1.0
      }
      window-rule {
          match app-id="Alacritty" is-active=false
          opacity 0.92
      }
      window-rule {
          match is-floating=true
          geometry-corner-radius 14
          opacity 0.97
      }
      window-rule {
          match app-id=r#"firefox$"# title="^Picture-in-Picture$"
          open-floating true
      }
      window-rule {
          match title="^Picture-in-Picture$"
          geometry-corner-radius 16
          default-column-width { fixed 480; }
          default-window-height { fixed 270; }
      }

      // Per-host autostart: waybar + wallpaper restore + notifications.
      // Hosts can override these via config.d/ overrides.
      spawn-at-startup "waybar"
      spawn-sh-at-startup "set-wallpaper restore"
      spawn-at-startup "mako"

      binds {
          Mod+Shift+Slash { show-hotkey-overlay; }

          Mod+Return hotkey-overlay-title="Open a Terminal: alacritty" { spawn "alacritty"; }
          Mod+T      hotkey-overlay-title="Open a Terminal: alacritty" { spawn "alacritty"; }
          Mod+Space  hotkey-overlay-title="Run an Application: fuzzel" { spawn "fuzzel"; }
          Mod+D      hotkey-overlay-title="Run an Application: fuzzel" { spawn "fuzzel"; }
          Super+Alt+L hotkey-overlay-title="Lock the Screen: swaylock" { spawn "swaylock"; }
          Mod+Shift+W hotkey-overlay-title="Random Wallpaper" { spawn "set-wallpaper"; }

          XF86AudioRaiseVolume allow-when-locked=true { spawn-sh "wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+ -l 1.0"; }
          XF86AudioLowerVolume allow-when-locked=true { spawn-sh "wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-"; }
          XF86AudioMute        allow-when-locked=true { spawn-sh "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"; }
          XF86AudioMicMute     allow-when-locked=true { spawn-sh "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"; }

          XF86AudioPlay allow-when-locked=true { spawn-sh "playerctl play-pause"; }
          XF86AudioStop allow-when-locked=true { spawn-sh "playerctl stop"; }
          XF86AudioPrev allow-when-locked=true { spawn-sh "playerctl previous"; }
          XF86AudioNext allow-when-locked=true { spawn-sh "playerctl next"; }

          XF86MonBrightnessUp   allow-when-locked=true { spawn "brightnessctl" "--class=backlight" "set" "+10%"; }
          XF86MonBrightnessDown allow-when-locked=true { spawn "brightnessctl" "--class=backlight" "set" "10%-"; }

          Mod+O repeat=false { toggle-overview; }
          Mod+Q repeat=false { close-window; }

          Mod+Left  { focus-column-left; }
          Mod+Down  { focus-window-down; }
          Mod+Up    { focus-window-up; }
          Mod+Right { focus-column-right; }
          Mod+H     { focus-column-left; }
          Mod+J     { focus-window-down; }
          Mod+K     { focus-window-up; }
          Mod+L     { focus-column-right; }

          Mod+Ctrl+Left  { move-column-left; }
          Mod+Ctrl+Down  { move-window-down; }
          Mod+Ctrl+Up    { move-window-up; }
          Mod+Ctrl+Right { move-column-right; }
          Mod+Ctrl+H     { move-column-left; }
          Mod+Ctrl+J     { move-window-down; }
          Mod+Ctrl+K     { move-window-up; }
          Mod+Ctrl+L     { move-column-right; }

          Mod+Home { focus-column-first; }
          Mod+End  { focus-column-last; }

          Mod+Page_Down { focus-workspace-down; }
          Mod+Page_Up   { focus-workspace-up; }
          Mod+U         { focus-workspace-down; }
          Mod+I         { focus-workspace-up; }

          Mod+Shift+Page_Down { move-workspace-down; }
          Mod+Shift+Page_Up   { move-workspace-up; }
          Mod+Shift+U         { move-workspace-down; }
          Mod+Shift+I         { move-workspace-up; }

          Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
          Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }
          Mod+Ctrl+WheelScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
          Mod+Ctrl+WheelScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

          Mod+1 { focus-workspace 1; }
          Mod+2 { focus-workspace 2; }
          Mod+3 { focus-workspace 3; }
          Mod+4 { focus-workspace 4; }
          Mod+5 { focus-workspace 5; }
          Mod+6 { focus-workspace 6; }
          Mod+7 { focus-workspace 7; }
          Mod+8 { focus-workspace 8; }
          Mod+9 { focus-workspace 9; }

          Mod+Shift+1 { move-column-to-workspace 1; }
          Mod+Shift+2 { move-column-to-workspace 2; }
          Mod+Shift+3 { move-column-to-workspace 3; }
          Mod+Shift+4 { move-column-to-workspace 4; }
          Mod+Shift+5 { move-column-to-workspace 5; }
          Mod+Shift+6 { move-column-to-workspace 6; }
          Mod+Shift+7 { move-column-to-workspace 7; }
          Mod+Shift+8 { move-column-to-workspace 8; }
          Mod+Shift+9 { move-column-to-workspace 9; }

          Mod+R { switch-preset-column-width; }
          Mod+Shift+R { reset-window-height; }
          Mod+F       { maximize-column; }
          Mod+Shift+F { fullscreen-window; }
          Mod+C       { center-column; }

          Print { screenshot; }
          Ctrl+Print { screenshot-screen; }
          Alt+Print  { screenshot-window; }

          Mod+Shift+E { quit; }
          Mod+Shift+P { power-off-monitors; }
      }
    '';
  };
}
