# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-93c4934a-b273-4295-aaec-1896b8c12b9b";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-93c4934a-b273-4295-aaec-1896b8c12b9b".device = "/dev/disk/by-uuid/93c4934a-b273-4295-aaec-1896b8c12b9b";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-93c4934a-b273-4295-aaec-1896b8c12b9b";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-93c4934a-b273-4295-aaec-1896b8c12b9b";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C368-29C8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # nixos-generate-config emitted `swapDevices = [ ]` (it ran before swapon
  # during the LUKS reinstall); nvme0n1p2 is a real 103G swap partition.
  # NOTE: mkForce-overridden by ./luks.nix (randomEncryption, by-partuuid) —
  # the plain by-uuid entry below is inert.
  swapDevices =
    [ { device = "/dev/disk/by-uuid/a6f67c76-04be-4769-b201-de2a48ec110b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
