# Encryption policy for oerlikon on top of the installer-generated LUKS/btrfs
# layout. Root unlock itself is declared in hardware-configuration.nix
# (boot.initrd.luks.devices."luks-93c4934a-..."); this module only layers
# policy on top of it.
#
# History: the original plan was an in-place `cryptsetup reencrypt` of the old
# ext4 root, but the disk was instead wiped and reinstalled as LUKS2 + btrfs,
# which obsoleted the staged migration runbook.
{ lib, ... }:

{
  # Pass TRIM through dm-crypt; root sits on an NVMe SSD. Trade-off: TRIM
  # reveals which sectors are unused (allocation patterns) to the disk
  # firmware and to anyone reading the raw device. Accepted here — the
  # SOC2 control is data-at-rest confidentiality, not pattern hiding —
  # and applied consistently to swap below.
  boot.initrd.luks.devices."luks-93c4934a-b273-4295-aaec-1896b8c12b9b".allowDiscards = true;

  # Overrides the swapDevices in hardware-configuration.nix — that file is
  # regenerated by nixos-generate-config, so we mkForce here instead of
  # editing it. randomEncryption keys the swap with a fresh random key on
  # every boot, so the swap fs UUID dies each boot and the device must be
  # referenced by PARTUUID. Safe on oerlikon: nothing configures hibernation
  # (logind default lid action is plain suspend), so resume-from-swap is not
  # needed.
  swapDevices = lib.mkForce [
    {
      # nvme0n1p2 — `lsblk -no PARTUUID /dev/nvme0n1p2`.
      device = "/dev/disk/by-partuuid/2c87c775-5dcb-47f7-9af2-ad500a213d28";
      randomEncryption = {
        enable = true;
        # Same TRIM policy (and the same allocation-pattern disclosure) as
        # the root device above.
        allowDiscards = true;
      };
    }
  ];
}
