# LUKS unlock for oerlikon's in-place encrypted root, plus encrypted swap.
#
# STAGED — do NOT import this file until the cryptsetup reencrypt migration
# has run. The root partition is still plain ext4; importing earlier builds
# an initrd that waits forever for a LUKS device that does not exist.
# Runbook: ./LUKS-MIGRATION.md. After the migration, replace @LUKS_UUID@ and
# @SWAP_PARTUUID@ with real values and add ./luks.nix to ./default.nix.
#
# fileSystems."/" in hardware-configuration.nix needs NO change: cryptsetup
# reencrypt preserves the ext4 filesystem, so its UUID survives. Once the
# initrd unlocks cryptroot, the same /dev/disk/by-uuid symlink points at the
# mapper device instead of the raw partition.
{ lib, ... }:

{
  boot.initrd.luks.devices."cryptroot" = {
    # LUKS header UUID — `cryptsetup luksUUID <rootpart>` after migration.
    device = "/dev/disk/by-uuid/@LUKS_UUID@";
    # Pass TRIM through dm-crypt; root sits on an NVMe SSD.
    allowDiscards = true;
  };

  # Overrides the generated swapDevices in hardware-configuration.nix — that
  # file is regenerated by nixos-generate-config, so we mkForce here instead
  # of editing it. randomEncryption keys the swap with a fresh random key on
  # every boot, so the old swap fs UUID dies and the device must be referenced
  # by PARTUUID. Safe on oerlikon: nothing configures hibernation (logind
  # default lid action is plain suspend), so resume-from-swap is not needed.
  swapDevices = lib.mkForce [
    {
      # `lsblk -no PARTUUID <swappart>` after migration.
      device = "/dev/disk/by-partuuid/@SWAP_PARTUUID@";
      randomEncryption.enable = true;
    }
  ];
}
